name: blue_sky_station
description: "A new Flutter project."

publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  xor_dart: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  lottie: ^3.0.0
  awesome_dialog: ^3.2.0
  crypto: ^3.0.3
  intl: ^0.19.0
  flip_panel_plus: ^1.0.0+3
  cupertino_icons: ^1.0.2
  connectivity_plus: ^6.0.3
flutter_localizations:
  sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
